[package]
name = "normfs-io-benchmark"
version = "0.0.0"
edition = "2024"
publish = false

[workspace]

[features]
macos-ssd = []

[dependencies]
normfs-fs = { path = "../../normfs-fs" }
bytes = "1"
libc = "0.2"
serde_json = "1"
tempfile = "3"
tokio = { version = "1", features = ["full"] }

[[bin]]
name = "fs_io"
path = "main.rs"

[[bin]]
name = "ssd_io"
path = "ssd.rs"
required-features = ["macos-ssd"]
